language: ruby

rvm:
  - 2.4.2

addons:
  chrome: stable

before_script:
  - bin/setup

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rails webpacker:compile
  - bundle exec rails ci
